import Anthropic from "@anthropic-ai/sdk";
import { logger } from "@/lib/logger";

export interface CopyInput {
  productName: string;
  category: string;
  description?: string;
  brandName?: string;
  targetAudience?: string;
  tone?: string;
}

export interface CopyKit {
  listingTitle: string;
  listingDescription: string;
  adHeadline: string;
  adBody: string;
  socialCaption: string;
  emailSubjectLine: string;
  seoTitle: string;
  seoDescription: string;
  disclaimer: string;
}

export const COPY_DISCLAIMER =
  "This copy was generated by AI and is a starting point for human review and editing. " +
  "Review all claims for accuracy before publishing.";

function deterministicHash(s: string): number {
  let h = 0;
  for (const c of s) h = (Math.imul(31, h) + c.charCodeAt(0)) | 0;
  return Math.abs(h);
}

function pick<T>(arr: T[], seed: number, salt: string): T {
  const h = deterministicHash(`${seed}${salt}`);
  return arr[h % arr.length]!;
}

const HEADLINES = [
  "Finally, the {n} that works as hard as you do",
  "Discover {n} — your everyday essential",
  "Upgrade your life with {n}",
  "The smarter way: {n}",
  "Meet the {n} everyone's talking about",
];

const AD_BODIES = [
  "Crafted for people who refuse to settle. {n} delivers quality you can feel from day one. Free shipping on all orders.",
  "Stop scrolling and start living. {n} is everything you've been looking for — without the premium price tag.",
  "Thousands of happy customers have already made the switch to {n}. Join them and see the difference.",
];

const SOCIAL_CAPTIONS = [
  "Obsessed with {n} right now ✨ Link in bio to grab yours!",
  "This {n} is giving us all the feels 🙌 Tap to shop before it sells out.",
  "POV: You just found the {n} you didn't know you needed. Shop the link 🔗",
];

const EMAIL_SUBJECTS = [
  "You're going to love this: {n} just dropped",
  "Your {n} is waiting for you 👀",
  "New in: {n} — better than you'd expect",
];

const fill = (t: string, n: string) => t.replace(/{n}/g, n);

function generateDemoCopy(input: CopyInput): CopyKit {
  const h = deterministicHash(input.productName + input.category);
  const n = input.productName;
  const brand = input.brandName ? ` by ${input.brandName}` : "";

  return {
    listingTitle: `${n}${brand} — Premium Quality, Unbeatable Value`,
    listingDescription:
      `Experience the best with ${n}. ` +
      `Designed for ${input.targetAudience ?? "everyday use"}, this product combines ` +
      `durability, style, and functionality. ${input.description ?? "The perfect addition to your lifestyle."}`,
    adHeadline:       fill(pick(HEADLINES, h, "h"), n),
    adBody:           fill(pick(AD_BODIES, h, "b"), n),
    socialCaption:    fill(pick(SOCIAL_CAPTIONS, h, "s"), n),
    emailSubjectLine: fill(pick(EMAIL_SUBJECTS, h, "e"), n),
    seoTitle:         `${n} — Buy Online | ${input.brandName ?? "Best Deals"}`,
    seoDescription:
      `Shop ${n} online. ${(input.description ?? "").slice(0, 100) || "Premium quality product"} ` +
      `with fast delivery and easy returns.`,
    disclaimer: COPY_DISCLAIMER,
  };
}

const SYSTEM_PROMPT = `You are an expert e-commerce copywriter for dropshipping stores.
Generate compelling, conversion-optimised marketing copy for the product described.
Return ONLY a valid JSON object — no markdown, no preamble.

Required fields (all strings):
{
  "listingTitle": "under 80 chars, clear and benefit-driven",
  "listingDescription": "100-200 words, features + benefits, honest and specific",
  "adHeadline": "under 40 chars, attention-grabbing, no clickbait",
  "adBody": "50-100 words, persuasive, clear CTA",
  "socialCaption": "under 150 chars, conversational, 1-2 emoji",
  "emailSubjectLine": "under 50 chars, creates genuine curiosity",
  "seoTitle": "50-60 chars, includes product name and key benefit",
  "seoDescription": "under 160 chars, descriptive and click-worthy"
}

Rules:
- No superlatives like "best ever", "world's greatest", "guaranteed results"
- No false urgency or deceptive claims
- Active voice throughout
- Match tone to product category`;

export async function generateCopyKit(input: CopyInput): Promise<CopyKit> {
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (apiKey) {
    try {
      const client = new Anthropic({ apiKey });
      const prompt = [
        `Product: ${input.productName}`,
        `Category: ${input.category.replace(/_/g, " ")}`,
        input.description    ? `Description: ${input.description}`       : null,
        input.brandName      ? `Brand: ${input.brandName}`               : null,
        input.targetAudience ? `Target audience: ${input.targetAudience}`: null,
        input.tone           ? `Tone: ${input.tone}`                     : null,
      ]
        .filter(Boolean)
        .join("\n");

      const response = await client.messages.create({
        model: "claude-sonnet-4-6",
        max_tokens: 1024,
        system: SYSTEM_PROMPT,
        messages: [{ role: "user", content: prompt }],
      });

      const text = response.content[0]?.type === "text" ? response.content[0].text : "";
      const parsed = JSON.parse(text) as Partial<CopyKit>;

      return {
        listingTitle:       String(parsed.listingTitle      ?? ""),
        listingDescription: String(parsed.listingDescription ?? ""),
        adHeadline:         String(parsed.adHeadline        ?? ""),
        adBody:             String(parsed.adBody            ?? ""),
        socialCaption:      String(parsed.socialCaption     ?? ""),
        emailSubjectLine:   String(parsed.emailSubjectLine  ?? ""),
        seoTitle:           String(parsed.seoTitle          ?? ""),
        seoDescription:     String(parsed.seoDescription    ?? ""),
        disclaimer:         COPY_DISCLAIMER,
      };
    } catch (err) {
      logger.warn({ err }, "Anthropic copy generation failed; falling back to demo");
    }
  }

  return generateDemoCopy(input);
}
